require: rubocop-performance

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15
  Exclude:
    - apps/*/action.rb

Metrics/BlockLength:
  Exclude:
    - db/**/*
    - spec/**/*
    - config/**/*
    - lib/tasks/**/*
  AllowedMethods:
    - configure
    - schema
    - params
    - nested

#Metrics/ModuleLength:
#  Exclude:
#    - apps/*/application.rb
#
#Layout/SpaceBeforeBrackets:
#  Exclude:
#    - db/migrations/*
#    - spec/support/fabricators/*

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SingleLineBlockChain:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*'

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/NumberConversion:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Performance/ChainArrayAllocation:
 Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Send:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/**/*'

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/IfUnlessModifier:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/IpAddresses:
  Exclude:
    - spec/**/*

Style/NumericLiterals:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/**/*

Style/SlicingWithRange:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Performance/BigDecimalWithNumericArgument:
  Enabled: false
