default: &default

  adapter: postgresql

  encoding: unicode

  pool: <%= ENV.fetch('MAX_THREADS') { 5 } %>

  username: <%= ENV.fetch('DATABASE_USER') %>

  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

  host: <%= ENV.fetch('DATABASE_HOST') %>

  port: <%= ENV.fetch('DATABASE_PORT') %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') %>

test:
  <<: *default
  database: observer-test

staging:

  <<: *default

production:

  <<: *default