# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rspec:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: observer-test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Setup DB, Run tests
        env:
#          PGHOST: postgres
#          PGUSER: postgres
#          PGPORT: ${{ job.services.postgres.ports[5432] }}

          DATABASE_HOST: postgres
          DATABASE_NAME: observer-test
          DATABASE_USER: postgres
          DATABASE_PASSWORD: ""
          DATABASE_PORT: 5432
          SCHEMA: "db/schema.rb"
          ENVIRONMENT: test
        run: |
          rake db:create db:schema:load
          bundle exec rspec
